create database Consulta

use Consulta

create table [AGENDAMENTOS](
[ID_AGENDA] INT IDENTITY,
[FK_CLIENTE]INT NOT NULL,
[DATA_AGENDA]DATE,
[OBESERVACAO] VARCHAR(200)
PRIMARY KEY ([ID_AGENDA])
FOREIGN KEY ([FK_CLIENTE]) REFERENCES [CLIENTES](ID_CLIENTE)
);

create table [CLIENTES](
[ID_CLIENTE]INT IDENTITY PRIMARY KEY,
[NOME_CLI] VARCHAR(100),
[DATA_NASCIMENTO]DATE,
[SEXO]CHAR(1),
CONSTRAINT [CHECK_SEXO]
	CHECK(SEXO IN('M','F'))
);


insert into CLIENTES values ('Vitor','1995/12/11','M')
insert into CLIENTES values ('Vivian','1997-04-01','F')

insert into AGENDAMENTOS values (2,getdate(),'Marcado as 15 horas')
insert into AGENDAMENTOS values (3,getdate(),'Marcado as 16 horas')
insert into AGENDAMENTOS values (2,'2020/09/23','REMARCADO')


SELECT B.NOME_CLI,B.SEXO,A.DATA_AGENDA,A.OBESERVACAO
FROM AGENDAMENTOS A
	INNER JOIN CLIENTES B
		ON A.FK_CLIENTE=B.ID_CLIENTE
ORDER BY NOME_CLI